JSON logging for balloon pops via ISViewer64
    make DEBUG=1 AVOID_UB=1 NON_MATCHING=1

Can be seen on real hardware via:

    sc64deployer upload build/us/mk64.us.z64
    sc64deployer debug --isv 0x03FF0000

Or on emulator via:

    ares build/us/mk64.us.z64

Note that before this successful attempt I made two unfruitful attempts
on getting debug logging to work with:

- Integrating libdragon's `debugf()`
- Integrating N64-UNFLoader's Debug library

In the libdragon attempt I couldn't get the mixture of libultra and
libdragon to build.
I did manage to integrat the UNFLoader library into the build but when
starting the resulting ROM on real hardware nothing showed up.

I have no idea why we need to change gISVDbgPrnAdrs away from 0xB3FF0000
to 0x03FF0000, but I get the following error if I try to use the former
address in sc64deployer:

    sc64deployer debug --isv 0xB3FF0000
    error: invalid value '0xB3FF0000' for '--isv <offset>': exceeds maximum of 67043328